Add audit support to kernel as required by lima
Otherwise the lima-guestagent fails to start up properly:

Error: audit not supported by kernel: protocol not supported